"""mime

Revision ID: 65923a2f6e59
Revises: 623c1a9700df
Create Date: 2024-12-18 13:44:56.020899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65923a2f6e59'
down_revision = '623c1a9700df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.alter_column(
            'photo',
            existing_type=sa.String(length=255),
            type_=sa.LargeBinary(),
            existing_nullable=True,
            postgresql_using="photo::bytea"  # Voeg deze regel toe
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.alter_column('photo',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('photo_mime')

    # ### end Alembic commands ###
