"""Add rating and rating_count to Technician

Revision ID: 799c2a7a2188
Revises: 8164452c243a
Create Date: 2024-12-16 22:25:19.201678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '799c2a7a2188'
down_revision = '8164452c243a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technicians', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('rating_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technicians', schema=None) as batch_op:
        batch_op.drop_column('rating_count')
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
