"""Add conversations relationship to Technician model

Revision ID: b89fbf385a55
Revises: fbcd79d72846
Create Date: 2024-12-18 20:06:34.576081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b89fbf385a55'
down_revision = 'fbcd79d72846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technicians', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('rating_count',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technicians', schema=None) as batch_op:
        batch_op.alter_column('rating_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)

    # ### end Alembic commands ###
