"""Add conversations table and conversation_id to chat_messages

Revision ID: bd96f729c1f4
Revises: c58492e414c4
Create Date: 2024-12-18 17:24:30.504367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd96f729c1f4'
down_revision = 'c58492e414c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_1', sa.String(length=80), nullable=False),
    sa.Column('participant_2', sa.String(length=80), nullable=False),
    sa.Column('last_message_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversation_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'conversations', ['conversation_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('conversation_id')

    op.drop_table('conversations')
    # ### end Alembic commands ###
