"""FK conversations

Revision ID: d24e475b47a7
Revises: bd96f729c1f4
Create Date: 2024-12-18 17:43:32.862209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd24e475b47a7'
down_revision = 'bd96f729c1f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participant_1_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('participant_2_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'students', ['participant_1_id'], ['id'])
        batch_op.create_foreign_key(None, 'technicians', ['participant_2_id'], ['id'])
        batch_op.drop_column('participant_1')
        batch_op.drop_column('participant_2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participant_2', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('participant_1', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('participant_2_id')
        batch_op.drop_column('participant_1_id')

    # ### end Alembic commands ###
