"""nullable

Revision ID: f2f94d02763b
Revises: d24e475b47a7
Create Date: 2024-12-18 18:22:17.588906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2f94d02763b'
down_revision = 'd24e475b47a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('technician_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('conversations_participant_2_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('conversations_participant_1_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'])
        batch_op.create_foreign_key(None, 'technicians', ['technician_id'], ['id'])
        batch_op.drop_column('participant_1_id')
        batch_op.drop_column('participant_2_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participant_2_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('participant_1_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('conversations_participant_1_id_fkey', 'students', ['participant_1_id'], ['id'])
        batch_op.create_foreign_key('conversations_participant_2_id_fkey', 'technicians', ['participant_2_id'], ['id'])
        batch_op.drop_column('technician_id')
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###
